rvm:
  - 1.9.3
before_script: "sudo apt-get -y install zip unzip"
before_script: "cp config/users.yml.example config/users.yml"
before_script: "cp config/config.yml.example config/config.yml"
branches:
  only:
      - master
