rvm:
  - 1.9.3
services: mysql
bundler_args: --without development
before_script: 
  - "sudo apt-get -y install zip unzip"
  - "cp config/users.yml.example config/users.yml; cp config/config.yml.example config/config.yml"
  - "rake db:create:test"
  - "rake db:migrate RACK_ENV=test"
  - "rake db:seed RACK_ENV=test"
branches:
  only:
      - master
