---
- Abstract
- Accessioned Date
- Advisor Contributor
- Alternative Title Type
- Author
- Available Date
- Citation 
- Classification Subject
- Contributor
- Contributor Coverage
- Copyright Date
- Created
- Date
- Date
- Ddc Subject
- Description
- Description
- Description
- Editor Contributor
- Extent 
- Filename Contributor
- Format
- Govdoc Identifier
- Haspart Relation
- Hasversion Relation
- Holder Rights
- Identifier
- Identifier
- Identifier Language
- Illustrator Contributor
- Isbasedon 
- Isbn Identifier
- Isformatof Relation
- Ismn Identifier
- Iso Language
- Ispartof Relation
- Ispartofseries 
- Isreferencedby Relation
- Isreplacedby Relation
- Issn 
- Issued Date
- Isversionof 
- Lcc Subject
- Lcsh 
- Medium Format
- Mesh Subject
- Mimetype Format Identifier
- Other
- Other Identifier
- Other Subject Title
- Provenance Description
- Relation
- Relation
- Relation
- Relation
- Replaces Relation
- Requires Relation
- Rights
- Sici Identifier
- Slug Identifier
- Spatial Coverage
- Sponsorship 
- Statementofresponsibility Description
- Subject
- Subject
- Submitted Date
- Tableofcontents 
- Temporal Creator
- Updated Date Description
- Uri 
- Uri Description
- Uri Relation 
- Uri Rights Source
- Uri Source 
- Version Description Format
- rfc3066 Language Publisher 
